# Site settings
title: Alessandro Sartori
email: alex.sartori1997@gmail.com
description: >-
    I'm Alessandro Sartori, an italian developer with many interests.
    This is my porfolio, be sure to checkout my projects and my blog,
    where I write about them and about many other things I build and
    experiment with.
baseurl: ""
url: "https://alexsartori.github.io"
permalink: /blog/:categories/:title

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

# Other
sass:
  sass_dir: css
  style: compressed
