# Site settings
title: Alessandro Sartori
email: alex.sartori1997@gmail.com
description: >-
    I'm Alessandro Sartori, an italian developer with many interests.
    This is my porfolio, be sure to checkout my projects and my blog,
    where I write about them and about many other things I build and
    experiment with.
baseurl: ""
url: "https://alexsartori.github.io"
permalink: /blog/:categories/:title

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect

# Other
sass:
  sass_dir: css
  style: compressed

# google_site_verification: ...

# jekyll-seo-tag
author: alex__sartori
twitter:
  username: alex__sartori
  card: summary
social:
  name: Alessandro Sartori
  links:
    - https://twitter.com/alex__sartori
    - https://github.com/AlexSartori
    - https://www.linkedin.com/in/alessandro-sartori-92a567100/
    - https://www.hackerrank.com/alexsartori
    - https://www.goodreads.com/user/show/88443905-alex-sartori
